/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()								//Co robi: Pusta funkcja. Do czego: Może być używana przez debugery (SWO, semihosting), ale w większości projektów nic nie robi.
{
}

int _getpid(void)												//Co robi: Zwraca identyfikator procesu. W STM32: Zawsze zwraca 1 – bo mikrokontroler nie ma procesów.
{
  return 1;
}

int _kill(int pid, int sig)										//Co robi: Wysyła sygnał do procesu. W STM32: Zawsze zwraca błąd (-1), bo nie ma procesów.
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)											//Kończy program.W STM32: Wywołuje _kill() i wchodzi w nieskończoną pętlę (while(1){}) – program po prostu “zawiesza się”.
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)	//Co robi: Czyta dane z pliku (np. stdin). W STM32: Czyta dane z funkcji __io_getchar() (np. UART), zapisuje je do ptr.
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)	//Co robi: Zapisuje dane do pliku (np. stdout).W STM32: Wysyła każdy znak przez __io_putchar() (np. UART).Dzięki temu działa printf().
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

int _close(int file)											//Co robi: Zamknięcie pliku.W STM32: Zawsze zwraca -1 – brak obsługi plików.
{
  (void)file;
  return -1;
}


int _fstat(int file, struct stat *st)							//Co robi: Zwraca informacje o pliku.W STM32: Zwraca, że plik jest urządzeniem znakowym (S_IFCHR) – np. terminal/UART
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file)											//Co robi: Sprawdza, czy plik jest terminalem.W STM32: Zawsze 1 – traktujemy UART jako terminal.
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir)							//Co robi: Przesuwa wskaźnik w pliku.W STM32: Zawsze 0 – nie ma plików, nie ma sensu.
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(char *path, int flags, ...)			//Co robi: Otwiera plik.W STM32: Zawsze zwraca -1 – brak systemu plików.
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(int *status)		//Co robi: Czeka na zakończenie procesu.W STM32: Zawsze zwraca błąd (-1) – brak procesów.
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)		//Co robi: Usuwa plik.W STM32: Zawsze błąd – brak systemu plików.
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf)			//Co robi: Zwraca czas procesów.W STM32: Zawsze -1 – brak procesów/systemu.
{
  (void)buf;
  return -1;
}

int _stat(char *file, struct stat *st)	//Co robi: Zwraca informacje o pliku.W STM32: Jak _fstat() – mówi, że to urządzenie znakowe.
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)		//Co robi: Tworzy link symboliczny do pliku.W STM32: Zawsze błąd (-1) – brak plików.
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)					//Co robi: Tworzy nowy proces.W STM32: Zawsze błąd (-1) – brak OS/procesów.
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)			//Co robi: Uruchamia nowy program.W STM32: Zawsze błąd (-1) – brak systemu do uruchamiania procesów.
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
